import 'bootstrap/dist/css/bootstrap.css'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from './components/Navbar/Navbar';
import Footer from './components/Footer/Footer';
import BootstrapClient from './components/BootstrapClient';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Usafihub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className='fw-light'>
        <Navbar />
          {children}
        <Footer />
      </body>
      <BootstrapClient />
    </html>
  );
}
